### PR TITLE
Fix duplicate requests

### PR DESCRIPTION
**Pull request by carloshungwhs**
Use on request  events to parse requests and responses instead of beforeDone event.

### CODE REVIEW

**Review by fervidnerd — DISMISSED** [review]
Out of curiosity - how come did we originally get duplicates?

**Review by ericsheridanwhs — DISMISSED** [review]

**Comment by vbisbest** [comment]
The issue with the timestamps is caused by this line.  Lets discuss.
https://github.com/whitehatsec-innovations/newman-reporter-har/blob/d7dd80d590ccdf1ff84f9fe9dad212fa4e0c9688/index.js#L88

**Comment by carloshungwhs** [comment]
@hpapaxen commented
>  Out of curiosity - how come did we originally get duplicates?

Because the har file is created in the newman `beforeDone` event. In this event, newman reported the **same** request-response transaction for a [pre-request](https://github.com/whitehatsec-innovations/id-dast/blob/main/testdata/postman/TiredfulAPI.postman_collection.json#L233) and a request. That's why we see duplicates. _Note_: in this particular example using TiredfulAPI collection, a pre-request is a oauth request. Newman did not report this request in the `beforeDone` event.

In the newman `request` event is when I can see 2 different requests, a oauth and the actual request. That's where I made the fix.

**Comment by carloshungwhs** [comment]
@vbisbest commented
> The issue with the timestamps is caused by this line. Lets discuss.

Per our meeting on Wed, Aug 11 at 11:30 AM PT we agreed with your suggestion to move recording the execution timestamp on the newman `beforeDone` to `request` event.

**Review by vbisbest — APPROVED** [review]

**Comment by carloshungwhs** [comment]
@hpapaxen commented

> Ray has reported that the duplicate issue hasn't gone away

Just to keep the record straight, the issue was fixed in an earlier commit, https://github.com/whitehatsec-innovations/newman-reporter-har/pull/2/commits/d7dd80d590ccdf1ff84f9fe9dad212fa4e0c9688. He probably was using an old version, v. 1.02 since this fix in this pull request has not been published yet to https://www.npmjs.com/package/newman-reporter-har.

**Pull request merged**
